import { z } from 'zod';

// Post form validation schema (only title and content, slug is auto-generated by backend)
export const postFormSchema = z.object({
  title: z.string()
    .min(1, 'Title is required')
    .max(200, 'Title must be less than 200 characters'),
  post_content: z.string()
    .min(1, 'Content is required'),
});

// Full post schema (includes slug for reference)
export const postSchema = z.object({
  title: z.string().min(1).max(200),
  post_content: z.string().min(1),
  slug: z.string().min(1),
});

// Export TypeScript types from schemas
export type PostFormData = z.infer<typeof postFormSchema>;
export type PostData = z.infer<typeof postSchema>;
